### ISSUE TITLE
本地存储附件和图片路径问题

### ISSUE THREAD

**Issue by chunxingque** [fantasticit/think#258]
## 请描述功能点
私有化部署时，使用的是本地存储，当我使用nginx代理，把此地址修改了，原先的图片显示不了；我去看了数据库里的内容，图片和附件是绝对路径的形式。意味着如果如果私有化部署后，就不能修改附件和图片地址。如果后期想ip访问转域名域名，或者想迁移服务器，换了服务器的ip，原先的图片和附件就显示不了。这样不便于后期的系统维护。这个有啥好的方法解决吗？
```
oss:
  local:
    enable: true
    # 线上更改为服务端地址（如：https://api.codingit.cn）
    server: 'http://192.168.15.40/static/'
```

## 建议
 1. 图片和附件的路径使用相对路径，然后拼接路径访问
