### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by rexiamu** [fantasticit/think#288]
## 请描述功能点
如何进行子路径配置呢
例如：`http://think.codingit.cn/dev`

**Comment by rexiamu** [comment]
是否可以通过配置文件支持 nextjs 的 basePath
https://nextjs.org/docs/app/api-reference/config/next-config-js/basePath

**Comment by fantasticit** [comment]
https://github.com/fantasticit/think/blob/main/packages/client/next.config.js 参考其他配置，修改这个文件试下

**Comment by rexiamu** [comment]
如下配置不起作用

next.config.js
```js
const nextConfig = semi({
  experimental: {
    scrollRestoration: true,
    legacyBrowsers: false,
    browsersListForSwc: true,
  },
  basePath: config.basePath, // 新增
  assetPrefix: config.assetPrefix,
  env: {
    SERVER_API_URL: config.client.apiUrl,
    COLLABORATION_API_URL: config.client.collaborationUrl,
    ENABLE_OSS_S3: config.oss.s3.enable,
    DNS_PREFETCH: (config.client.dnsPrefetch || '').split(' '),
    SEO_APPNAME: config.client.seoAppName,
    SEO_DESCRIPTION: config.client.seoDescription,
    SEO_KEYWORDS: config.client.seoKeywords,
  },
  webpack: (config, { dev, isServer }) => {
    config.resolve.plugins.push(new TsconfigPathsPlugin());
    return config;
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  // FIXME: douyinfe 的第三方包存在 ts 类型错误！
  typescript: {
    ignoreBuildErrors: true,
  },
});
```

dev.yaml
```yaml
client:
  port: 5001
  assetPrefix: '/docs/' # 修改
  basePath: '/docs' # 修改
  apiUrl: 'http://localhost:5002/api'
  collaborationUrl: 'ws://localhost:5003'
  dnsPrefetch: '//wipi.oss-cn-shanghai.aliyuncs.com'
  siteUrl: 'http://localhost:5001'
  siteDomain: ''
```
