### ISSUE TITLE
docker-compose 安装，不支持arm架构

### ISSUE THREAD

**Issue by cklx0719** [fantasticit/think#69]
一开始就报错了：
[+] Running 0/2
 ⠇ mysql Pulling                                                                               2.8s
 ⠿ thinkdoc Error                                                                              2.7s
no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by fantasticit** [comment]
可以试下更改下 MySQL 的 image

**Comment by hxer520** [comment]
具体怎么改

**Comment by bigmoon929** [comment]
1. 修改 Dockerfile，指定`platform=linux/arm64`

```bash
FROM --platform=linux/arm64 node:18-alpine as builder
COPY . /app/
WORKDIR /app
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN npm config set registry http://mirrors.cloud.tencent.com/npm/
RUN npm i -g pm2 @nestjs/cli pnpm
RUN apk --no-cache add bash dos2unix \
    && find . -name "*.sh" -exec dos2unix {} \; \
    && apk del dos2unix
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN bash build-output.sh

FROM --platform=linux/arm64 node:18-alpine as prod
ENV TZ=Asia/Shanghai
COPY --from=builder /app/docker/* /app/docker/
COPY --from=builder /app/output/ /app/
WORKDIR /app
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN npm config set registry http://mirrors.cloud.tencent.com/npm/
RUN set -x \
    && apk update \
    && apk add --no-cache tzdata redis  \
    && chmod +x /app/docker/start.sh \
    && npm i -g pm2 @nestjs/cli pnpm \
    && rm -rf /var/cache/apk/*

ENTRYPOINT sh /app/docker/start.sh

```

2、修改 docker-compose.yaml，指定 platform，并修改 mysql 镜像

```yaml
version: '3'
services:
  think:
    build:
      context: .
    image: think
    platform: linux/arm64
    container_name: think
    volumes:
      - ./config:/app/config
      - ./runtime/static:/app/packages/server/static
    environment:
      - TZ=Asia/Shanghai
    expose:
      - '5001-5003'
    ports:
      - '5001-5003:5001-5003'
    depends_on:
      - mysql
      - redis
    networks:
      - think
  mysql:
    image: mysql:8.0.32
    platform: linux/arm64
    restart: always
    container_name: mysql-for-think
    volumes:
      - ./runtime/mysql:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=think
      - MYSQL_USER=think
      - MYSQL_PASSWORD=think
    expose:
      - '3306'
    ports:
      - '3306:3306'
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    networks:
      - think
  redis:
    image: redis:latest
    platform: linux/arm64
    restart: always
    container_name: redis-for-think
    command: >
      --requirepass root
    expose:
      - '6379'
    ports:
      - '6379:6379'
    volumes:
      - ./runtime/redis:/data
    privileged: true
    networks:
      - think
networks:
  think:
    driver: bridge
```

@hxer520  这应该能解决arm64机器安装部署的问题。Good Luck !!
